api = "/api/v1"
debug = true

[log]
rotation = "00:00"
retention = "3 days"
compression = "zip"

[http]
enable_cors = true
allow_origins = ["*"]
allow_headers = ["*"]
allow_methods = ["*"]
allow_credentials = true

[redis]
username = "admin"
password = "admin"
host = "localhost"
port = 6379
database = "0"
ssl = false

[database.master]
username = "postgres"
password = "postgres"
host = "localhost"
port = 5432
database = "dcie"
schema = "public"
pool_size = 5
pool_timeout = 30
pool_recycle = 3600
max_overflow = 5